section speakers
Dima-Davidenko/donut-Masters pull request #21
Opened 2022-09-29 12:42 UTC by Volin13

Розмітка

2022-09-29 12:42 UTC, Volin13 commented
Надіюсь не натупив)

2022-09-29 12:53 UTC, Dima-Davidenko commented on src/partials/speakers.html
> +                <img src="#" alt="Speaker Molly Rivera" width="130" height="131">
Размеры изображений разные для мобилки, таблетки и десктопа. Мы будем указывать их в css

2022-09-29 12:57 UTC, Dima-Davidenko requested changes

2022-09-29 12:57 UTC, Dima-Davidenko commented on src/partials/speakers.html
> +        <ul class="speakers">
по БЭМ нужно или блоку дать название speaker, потому что дальше у тебя идет speaker__item и т.д. Или все остальные элементы блока назвать speakers__item и т.д. Как по мне лучше второй вариант

2022-09-29 13:04 UTC, Dima-Davidenko commented on src/partials/speakers.html
> +                <img src="#" alt="Speaker Molly Rivera" width="130" height="131">
Также необходимо настроить prettier, у тебя табуляции по 4 пробела

2022-09-30 05:43 UTC, Dima-Davidenko approved these changes

2022-09-30 05:43 UTC, merged